//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJForLYW.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BJForLYW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap database_previous {
            get {
                object obj = ResourceManager.GetObject("database_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit_validated {
            get {
                object obj = ResourceManager.GetObject("edit-validated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap excel_alt_1 {
            get {
                object obj = ResourceManager.GetObject("excel_alt_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功是否打开 的本地化字符串。
        /// </summary>
        internal static string ExcelHelper_WriteToFile_导出成功是否打开 {
            get {
                return ResourceManager.GetString("ExcelHelper_WriteToFile_导出成功是否打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string ExcelHelper_WriteToFile_提示 {
            get {
                return ResourceManager.GetString("ExcelHelper_WriteToFile_提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功 的本地化字符串。
        /// </summary>
        internal static string Main_GetCofirmToDbToolStripButton1_Click_导入成功 {
            get {
                return ResourceManager.GetString("Main_GetCofirmToDbToolStripButton1_Click_导入成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要导入的入库文件 的本地化字符串。
        /// </summary>
        internal static string Main_GetCofirmToDbToolStripButton1_Click_请选择要导入的入库文件 {
            get {
                return ResourceManager.GetString("Main_GetCofirmToDbToolStripButton1_Click_请选择要导入的入库文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能出0个，改一下出库数量 的本地化字符串。
        /// </summary>
        internal static string Main_PutPartBtn_shebei_Click_ {
            get {
                return ResourceManager.GetString("Main_PutPartBtn_shebei_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功出库! 的本地化字符串。
        /// </summary>
        internal static string Main_PutPartBtn_shebei_Click_成功出库_ {
            get {
                return ResourceManager.GetString("Main_PutPartBtn_shebei_Click_成功出库_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写出库人 的本地化字符串。
        /// </summary>
        internal static string Main_PutPartBtn_shebei_Click_请填写出库人 {
            get {
                return ResourceManager.GetString("Main_PutPartBtn_shebei_Click_请填写出库人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要出库的备件 的本地化字符串。
        /// </summary>
        internal static string Main_PutPartBtn_shebei_Click_请选择要出库的备件 {
            get {
                return ResourceManager.GetString("Main_PutPartBtn_shebei_Click_请选择要出库的备件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此操作会重置备件库存表,除非你知道你在干什么,否则不要重新导入
        /// 如果有问题你可以单项修改或者从入库表导入来修改 的本地化字符串。
        /// </summary>
        internal static string Main_toolStripButton5_Click_ {
            get {
                return ResourceManager.GetString("Main_toolStripButton5_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string Main_保存SToolStripButton_Click_保存成功 {
            get {
                return ResourceManager.GetString("Main_保存SToolStripButton_Click_保存成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计控车间备件管理小程序
        ///给流氓做的
        ///不要指望它能做很多
        ///版权:崔健 的本地化字符串。
        /// </summary>
        internal static string Main_关于ToolStripMenuItem_Click_ {
            get {
                return ResourceManager.GetString("Main_关于ToolStripMenuItem_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计控车间备件管理小程序\n给流氓做的\n不要指望它能做很多\n版权:崔健 的本地化字符串。
        /// </summary>
        internal static string Main_关于ToolStripMenuItem_Click_版权_崔健 {
            get {
                return ResourceManager.GetString("Main_关于ToolStripMenuItem_Click_版权_崔健", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此行为会清除所有的数据库信息,除非你知道你在干什么,否则不要点确定
        ///确定要初始化数据库吗? 的本地化字符串。
        /// </summary>
        internal static string Main_清理数据库ToolStripMenuItem_Click_ {
            get {
                return ResourceManager.GetString("Main_清理数据库ToolStripMenuItem_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
